### ISSUE TITLE
Error spaming worldguard DIG_STONE

### ISSUE THREAD

**Issue by WolverStones** [MSWS/FreakyEnchants#3]
[Server thread/WARN]: [FreakyEnchants] Task #528 for FreakyEnchants v1.1.13 generated an exception
java.lang.NoSuchFieldError: DIG_STONE
	at org.mswsplex.enchants.utils.Utils.getBreakSound(Utils.java:120) ~[FreakyEnchants.jar:?]
	at org.mswsplex.enchants.checkers.pickaxe.WorldGuardExcavationCheck.lambda$0(WorldGuardExcavationCheck.java:88) ~[FreakyEnchants.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[minecraft_server.jar:git-Spigot-2cf50f0-2b93d83]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [minecraft_server.jar:git-Spigot-2cf50f0-2b93d83]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [minecraft_server.jar:git-Spigot-2cf50f0-2b93d83]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [minecraft_server.jar:git-Spigot-2cf50f0-2b93d83]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [minecraft_server.jar:git-Spigot-2cf50f0-2b93d83]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [minecraft_server.jar:git-Spigot-2cf50f0-2b93d83]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]

Final build for 1.12.2

**Comment by MSWS** [comment]
Thank you for reporting this bug. I will resolve it when I get the chance.

**Comment by MSWS** [comment]
Bug has been resolved in [v1.1.14](https://www.spigotmc.org/resources/freakyenchants-gui-npc-support-1-8-1-12-2.64154/update?update=269003)
